### ISSUE TITLE
it takes 2.3 seconds to import the package

### ISSUE THREAD

**Issue by ohad-alike** [pinecone-io/pinecone-python-client#104]
Hi,
It takes a very long time to load the sdk.
Are there any imports which can wait for the time they will be used?

**Comment by gdj0nes** [comment]
@ohad-alike thanks for reporting! we weren't able to reproduce this. Are you still seeing this issue? Sorry for the delayed response.

**Comment by ohad-alike** [comment]
Yes, 
` % time python -c "import pinecone"
python -c "import pinecone"  0.23s user 0.10s system 22% cpu 1.479 total`

**Comment by ohad-alike** [comment]
`from time import time`
`start = time()`
`import pinecone`
`print(f"time for import: {time()-start}")`

`time for import: 1.6446847915649414`

**Comment by micahjsmith** [comment]
this is obviously related to #189
