### ISSUE TITLE
async_req not well documented, types incorrect, async/await support?

### ISSUE THREAD

**Issue by SimonSchick** [pinecone-io/pinecone-python-client#123]
We are trying to run multiple api calls concurrently, we are using `async_req` for that.
Unfortunately the docs and types for this mode of operation are rather lacking.

Also an async/await variant would be very nice since ThreadPools do not play very nicely with async/await in general.

**Comment by rajat08** [comment]
@SimonSchick 
Currently, async requests have a very thing implementation in the client, and they rely on the simple interfaces generated by OpenAPI code generators. The preferred pattern is for the user to create their multithreading/multiprocessing pattern, where each thread/process works with an independent client instance. Something like this community [post](https://community.pinecone.io/t/grpc-insert-broken-pipe-and-timeouts/313/7).

However, we are aware of the shortcomings of this setup and are actively working on revamping the SDKs to support async requests natively. Feel free to let us know how else we can help you with your setup.

**Comment by miararoy** [comment]
hi @SimonSchick - I'm re-opening this issue to let you know that we have a new SDK rolling out, still in experimental mode

https://github.com/pinecone-io/pinecone-client

Migration is simple, you can see on the readme, and also - there's a new async/await implementation that solves your issue exactly 

see here : https://github.com/pinecone-io/pinecone-client#performance-tuning-for-upsering-large-datasets

Let us know if that helps! 

Roy
