### ISSUE TITLE
Is their any way to pull my vectors out of an index with the python client?

### ISSUE THREAD

**Issue by AndriyMulyar** [pinecone-io/pinecone-python-client#127]

**Comment by gdj0nes** [comment]
We don't have a bulk export functionality today. Can you describe a bit more how often you would want to do these exports and how large the underlying indexes are.

**Comment by edoliberty** [comment]
Do you mean something like fetch?

https://github.com/pinecone-io/pinecone-python-client/blob/f9c7c2c6375e3e315fb8a894b10f9ddc022e1ae3/pinecone/index.py#L216

https://docs.pinecone.io/reference/fetch

**Comment by AndriyMulyar** [comment]
I have a vector visualization tool that I want to use to visualize my
embeddings in pinecone. I precondition is that I can extract all vectors
I've added to my pinecone instance so I can load them into the
visualization tool.

**Comment by coyotespike** [comment]
I have the same question, for the same purpose. Currently I am getting the index statistics and then using the number of entries to guess at the ids, and do a fetch that way. Clearly this is not ideal, as I assume ids may change if an item is deleted!

**Comment by AndriyMulyar** [comment]
Can you share your code?

**Comment by adri1wald** [comment]
Haystack has a pretty funky approach to this: https://github.com/deepset-ai/haystack/blob/main/haystack/document_stores/pinecone.py#L549-L606

**Comment by philipk19238** [comment]
> We don't have a bulk export functionality today. Can you describe a bit more how often you would want to do these exports and how large the underlying indexes are.

I have a batch job daily that updates the vectors I store. Right now I'm using a very hacky solution by making dummy requests ([0] * 1536) and getting top_k of my index size.

100% need a way to fetch all the IDs from the DB.

**Comment by adri1wald** [comment]
Agreed, especially important as you make schema changes to the data stored in pinecone. Right now we have to recompute all the embeddings, which is slow. What I would prefer is being able to bulk export all the data, apply the necessary transforms, and then put it back in the same or a different index.

**Comment by daverigby** [comment]
For serverless indexes you can use the [new `list` and `list_pagnated` APIs](https://docs.pinecone.io/guides/data/list-record-ids) as of client v3.1.0.
