### ISSUE TITLE
PineconeProtocolError: Failed to connect; did you specify the correct index name?

### ISSUE THREAD

**Issue by pradeepdev-1995** [pinecone-io/pinecone-python-client#146]
After creating index when run the below command 
```index.describe_index_stats()``` it shows like ```PineconeProtocolError: Failed to connect; did you specify the correct index name?```
And ```pinecone.list_indexes()``` also returns the empty list ```[]```. But index creation was successful using
```
pinecone.init(api_key="key", environment="env") 
index = pinecone.Index("TAPAS2")
index
````
The above code returned ```<pinecone.index.Index at 04e2e0>```

**Comment by rajat08** [comment]
You must use the [`create_index` API ](https://docs.pinecone.io/reference/create_index) to create an index. `pinecone.Index("_name_")` is used to connect to an existing index.

**Comment by pradeepdev-1995** [comment]
Worked it. Thank you
