### ISSUE TITLE
Deprecate Numpy

### ISSUE THREAD

**Issue by philipk19238** [pinecone-io/pinecone-python-client#148]
I'm requesting to remove numpy as a dependency. It is barely used within the repository and creates such a large dependency that is unexpected from what is essentially an API wrapper. Anyone who is trying to deploy a lambda function to AWS that uses the pinecone client would have to create a custom numpy layer to support the pinecone client.

**Comment by tsah-alike** [comment]
We are using pinecone client from AWS lambda and we are unable to upgrade because of this issue. I suggest adding support in a dedicated package (as with grpc)

**Comment by daverigby** [comment]
This is fixed by #233 which moves Numpy to be a development-only dependancy (it's used in various unit tests). This was included in [v3.0.0](https://github.com/pinecone-io/pinecone-python-client/releases/tag/v3.0.0).
