### ISSUE TITLE
Compatiblility with Jina Docarray

### ISSUE THREAD

**Issue by NOT-HAL9000** [pinecone-io/pinecone-python-client#150]
I'm looking to use pinecone as the vector database backend with Jina but it doesn't seem to be supported natively in the Docarray repo yet (They support milvus and others). Is this something pinecone couple help implement and merge into Jina? I opened an issue with them [here](https://github.com/docarray/docarray/issues/1245)

**Comment by NOT-HAL9000** [comment]
@gdj0nes Hey Gareth, reaching out on behalf of the Jina.ai/docararay team to see if pinecone would like to help build a docarray connector. See discussion at: https://github.com/docarray/docarray/issues/1245 .

Thanks!

**Comment by NOT-HAL9000** [comment]
@benjaminran @rajat08

**Comment by anawishnoff** [comment]
Thank you for posting this! Updating this issue to say that unfortunately this is not on our team's roadmap for the near future.
