### ISSUE TITLE
protobuf 3.19.3 is a bit outdated and due to this I can not install pinecone[grpc]

### ISSUE THREAD

**Issue by FilipJByren** [pinecone-io/pinecone-python-client#151]
Hi,
I want to install the grpc driver for pinecone, however as it need protobuf 3.19.3, it is not compatible with googles internal packages we are dependent on. I would like if someone could update the protobuf package to a later version 🙏 

Way to test it is to try to install https://pypi.org/project/google-cloud-secret-manager/ in the same environment

**Comment by rajat08** [comment]
@FilipJByren, thanks for tagging this; there are a few other dependencies in our other services that block us proto upgrades; we are working on updating these across our internal systems.

**Comment by FilipJByren** [comment]
Thank you @rajat08 🙏

**Comment by FilipJByren** [comment]
Ping @rajat08

**Comment by karam-khanna** [comment]
+1 on this

**Comment by pmespresso** [comment]
+ 1

**Comment by HashemAlsaket** [comment]
+1

**Comment by TimurH** [comment]
+1

**Comment by skulltech** [comment]
+1

**Comment by aaalexlit** [comment]
Now I'm having the same problem but with protobuf 3.19.6
The rest of my dependencies require >=3.20.2
I see that the current code it's actually bumped `protobuf~=3.20.0`
Are you planning to release any time soon?
Thanks

**Comment by DeanSingh** [comment]
+1.

Any updated here as this is becoming unusable when using pinecone-client with Google Palm 2 and other google libraries.

**Comment by DeanSingh** [comment]
I found a workaround temporally.  In my notebook don't include google-generativeai and instead work with "pinecone-client[grpc]" and I was using Langchain's GooglePalmEmbeddings.  This gets me past the protobuf issue.

**Comment by osmanbaskaya** [comment]
Hi, can we get an update? Is there any ETA for updating the protos?

**Comment by caleb-artifact** [comment]
Having the same issue.  I can't install `google-cloud-bigquery[bqstorage]` and `pinecone-client[grpc]` at the same time with pdm.  Resolution just spins trying to find a compatible `google-cloud-core` package.

Kind of a bummer when you need to shuffle large amounts of data from BigQuery into Pinecone 😢

**Comment by mjvankampen** [comment]
I am hitting this issue as well.

**Comment by daverigby** [comment]
As of pinecone-python-client [v4.0.0](https://github.com/pinecone-io/pinecone-python-client/releases/tag/v4.0.0),  protobuf has been updated from 3.20.3 to 4.25.3 (the latest 4.x version).
