### ISSUE TITLE
Is there a request rate limit for Pinecone?

### ISSUE THREAD

**Issue by kovogo** [pinecone-io/pinecone-python-client#159]
When I try to send multiple upsert requests to Pinecone simultaneously using multithreading, I occasionally encounter connection timeouts, especially when dealing with large amounts of data. P.S. I'm using a free testing account. My Program run on Azure.

Env:
* python 3.10
* OS:  Ubuntu 20.04.5 LTS
* pinecone-client: 2.2.1

When I executed the `netstat -antp` command, I found that a connection sending upsert requests to Pinecone was consistently blocked (the number of requests in the send queue never changed), and after waiting for a while, the console printed a connection timeout error.

![image](https://user-images.githubusercontent.com/95118515/229406555-a3121ee6-00dd-4a79-a9ac-8499251616a5.png)

After waiting for a while...
![image](https://user-images.githubusercontent.com/95118515/229406619-ac4c5189-1034-412a-baa5-b070d76705d7.png)

I saw an error was print in stdout

![image](https://user-images.githubusercontent.com/95118515/229406735-af3548c1-d5aa-4056-b378-b0f9f2a0f95a.png)

Since this issue does not occur frequently, I would like to confirm whether I should implement rate limiting in my application.

**Comment by mikeyny** [comment]
GEtting the same issue from my side, not sure why

**Comment by rajat08** [comment]
hey @kovogo , when you send a large number of upserts that the index or the load balancer is unable to handle, they reject the request. However, it's likely a client implementation detail + the lb for this instance. If you are using the same client object across multiple threads you may see this.
