### ISSUE TITLE
init

### ISSUE THREAD

**Issue by Mukesh-Choudhary** [pinecone-io/pinecone-python-client#160]
AttributeError: module 'pinecone' has no attribute 'init'

**Comment by naineet-increff** [comment]
Install the latest  development version by the following command and it will work

`pip3 install git+https://git@github.com/pinecone-io/pinecone-python-client.git`

**Comment by victaphu** [comment]
Hi all, 
I had the same problem and it looks like the library changed. Check out:
https://pypi.org/project/pinecone-client/

This worked for me:
```
from pinecone import Pinecone
pc = Pinecone(api_key=api_key)
index = pc.Index(host='<host>')

```
Hope this helps someone out there, was a real head scratcher for me
