### ISSUE TITLE
[Bug] Pinecone defaults to us-west-gcp when used in VSCode terminal

### ISSUE THREAD

**Issue by michox** [pinecone-io/pinecone-python-client#167]
### Is this a new bug in the Pinecone Python client?

- [X] I believe this is a new bug in the Pinecone Python Client
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

```
import pinecone

api_key="MY KEY"
env="asia-southeast1-gcp"

pinecone.init(api_key=api_key, enviroment="asia-southeast1-gcp")
pinecone.whoami()
```
results in `HTTPError: ('401 Client Error: Unauthorized for url: https://controller.us-west1-gcp.pinecone.io/actions/whoami', 'API key is missing or invalid for the environment "us-west1-gcp". Check that the correct environment is specified.')`

### Expected Behavior

Should not try to adress us-west-gcp when asia southeast is referenced

### Steps To Reproduce

running on python 3.10.0 on windows. Happens only in Visual Studio Code (clean project, no virtual environment). Happens in a jupyter notebook and when entering python through powershell.

### Relevant log output

```shell
HTTPError: ('401 Client Error: Unauthorized for url: https://controller.us-west1-gcp.pinecone.io/actions/whoami', 'API key is missing or invalid for the environment "us-west1-gcp". Check that the correct environment is specified.')
```

### Environment

```markdown
- OS:Windows 10
- Python:3.10.0
- pinecone:2.2.1
```

**Comment by rajat08** [comment]
@michox there is a typo in your code , you've used `enviroment` as the variable, whereas it should be `environment`. 
We currently don't do strict checks on variables you pass, but we should add this. Thanks for the feedback!
