### ISSUE TITLE
[Feature] Make client available through conda-forge

### ISSUE THREAD

**Issue by BastianZim** [pinecone-io/pinecone-python-client#173]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing client functionality

### Describe the feature

Currently, the client can only be downloaded through pip. It would be great if the client could also be dowloaded via conda.
The most popular way to do that is through conda-forge. It is an open source platform that builds and distributes packages for conda. The process is easy and straightforward with tools such as [grayskull](https://github.com/conda/grayskull). 

Currently, it is not possible to do that, as the license does not allow redistribution.

Ref:
- https://conda-forge.org
- https://github.com/conda-forge
- https://github.com/pinecone-io/pinecone-python-client/blob/2265066d7caaefd474d3fe8ebd41346d2d4eff1b/LICENSE.txt#L13

### Describe alternatives you've considered

Install with pip

### Who will this benefit?

Every user that uses conda. Conda is heavily used in the scientific community and would open this tool up to it.

### Are you interested in contributing this feature?

I can submit the tool, I just need a different license that allows redistribution.

### Anything else?

I am a reviewer at conda-forge and can try to answer any questions that might occur.

**Comment by daverigby** [comment]
Note that as of [v3](https://github.com/pinecone-io/pinecone-python-client/releases/tag/v3.0.0) pinecone-client has been relicensed under Apache-2.0, which should address any redistribution issues, if anyone in the conda ecosystem wants to add `pinecone-client` to conda-forge.

**Comment by BastianZim** [comment]
Awesome, thank you!
