### ISSUE TITLE
[Feature] Support for Compatible dnspython Version for pinecone-client

### ISSUE THREAD

**Issue by rm2631** [pinecone-io/pinecone-python-client#183]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing client functionality

### Describe the feature

I'm encountering a compatibility issue when using pinecone-client in conjunction with eventlet. The problem arises due to conflicting dependencies with dnspython versions.

I need to use eventlet==0.30.2 on a gunicorn==20.1.0 due to breaking changes that were fixed but never released.

eventlet requires dnspython version 1.16.0, while pinecone-client needs a version of dnspython greater than 2.0.0. As a result, it's currently not possible to use both libraries simultaneously.

I kindly request support for a compatible version of dnspython that can work harmoniously with both pinecone-client and eventlet. This would enable users to benefit from the features provided by both libraries without facing conflicts or incompatibilities.

By supporting a compatible dnspython version, it would provide developers with the flexibility to leverage the power of pinecone-client alongside eventlet or other libraries with similar dependencies.

I appreciate your attention to this matter and look forward to a resolution that allows for seamless integration of pinecone-client in various environments.

### Describe alternatives you've considered

- Deploy both services individually on different servers
- Fork pinecone-client, strip features that need dnsclient > 1.16.0

I want to see if it can be done in the project before considering these alternatives.

### Who will this benefit?

Users of eventlet, gunicorn and pinecone will benefit from this change. This kind of use should be standard on Azure environments since they use gunicorn servers by default.

### Are you interested in contributing this feature?

Yes

**Comment by mithatcak** [comment]
same issue. unable to use eventlet with pinecone-client

**Comment by daverigby** [comment]
The dependency on dnspython was removed by #237, which was first included in [v3.0.0](https://github.com/pinecone-io/pinecone-python-client/releases/tag/v3.0.0).
