### ISSUE TITLE
[Feature] better way to disable show_progress

### ISSUE THREAD

**Issue by dashesy** [pinecone-io/pinecone-python-client#184]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing client functionality

### Describe the feature

When using Pinecone from langchain's `Pinecone.from_existing_index` there is no way to disable the progressbar. That it is by default True is odd, because this is like verbose output.

Please make this False by default and add an option to turn it on if needed

### Describe alternatives you've considered

Patch the code

**Comment by Pharbi** [comment]
It looks like this is something that could be taken up in LangChain itself, as its used in their usage of `upsert` queries. https://github.com/hwchase17/langchain/blob/57d8a3d1e8fd376d8db8772977870d01ee5e444e/langchain/vectorstores/pinecone.py#L95

**Comment by Pharbi** [comment]
Looks like it's been fully merged, you can now use `kwargs` to specify the way you want to interact with the pinecone client.
