### ISSUE TITLE
[Bug] index.delete(delete_all=True) does not delete everything

### ISSUE THREAD

**Issue by cssndrx** [pinecone-io/pinecone-python-client#186]
### Is this a new bug in the Pinecone Python client?

- [X] I believe this is a new bug in the Pinecone Python Client
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

After issuing `index.delete(delete_all=True)`, I still see vectors in `index.describe_index_stats()`. I am new to pinecone and very well could just be doing something wrong.

### Expected Behavior

I expect there to be 0 vectors after issuing a delete_all command

### Steps To Reproduce

index = pinecone.GRPCIndex(index_name)

(Pdb) index.delete(delete_all=True)

(Pdb) index.describe_index_stats()
{'dimension': 1536,
 'index_fullness': 0.1,
 'namespaces': {'no-vectors': {'vector_count': 0},
                'vectors': {'vector_count': 5},
                'vectors-copy': {'vector_count': 0}},
 'total_vector_count': 5}

### Environment

```markdown
- OS: OS X
- Python: 3.10.12
- pinecone:

pinecone-client==2.2.2
```

**Comment by igiloh-pinecone** [comment]
When you perform a vector operation like `upsert`, `query`, `fetch` and `delete` - you're always performing it on a given namespace. As the [documentation](https://docs.pinecone.io/docs/manage-data#delete-vectors-by-namespace) mentions, also the `delete(delete_all=True)` operation deletes all the vectors in a namespace.

This might be slightly confusing, but when you omit the `namespace=` argument, it doesn't mean "operate on the entire index" but rather performs the operate on the _default_ namespace (which is simply called `""`). So in your cases you upserted some vectors into the `no-vectors` namespace, but deleted from the `""` namespace - hence the vectors weren't deleted.  
 
I hope that helps!

P.S.  
The above is true for all pod types other then the Starter Plan's index, in which there is only one namespace.

**Comment by cssndrx** [comment]
Ah gotcha!! Thanks a ton @igiloh-pinecone !
