### ISSUE TITLE
[Bug] Failed to connect to all addresses

### ISSUE THREAD

**Issue by Abe410** [pinecone-io/pinecone-python-client#205]
### Is this a new bug in the Pinecone Python client?

- [X] I believe this is a new bug in the Pinecone Python Client
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am simply trying to delete a specific namespace within my index using the following code:

```
import os
import sys
import json
import pinecone

# pinecone key
pinecone_env = xxxx
pinecone_key =  xxxx

# Initializing index name
index_name = "index_name"
# index = pinecone.Index(index_name)
index = pinecone.GRPCIndex(index_name)
namespace='namespace'

# Initialize pinecone
pinecone.init(
    api_key=pinecone_key,  # find at app.pinecone.io
    environment=pinecone_env  # next to api key in console
)

# Delete namespace
index.delete(delete_all=True, namespace=namespace)

print('Namespace deleted')
```

Doing this, I get the following error:

`PineconeException: UNKNOWN:failed to connect to all addresses; last error: UNAVAILABLE: ipv4:34.127.5.128:443: recvmsg:Connection reset by peer {created_time:"2023-09-28T20:38:58.196686658+00:00", grpc_status:14}`

Would appreciate any insights into this

### Expected Behavior

Expected behavior was that the code would delete the specific namespace as requested.

### Steps To Reproduce

Use grpc-gateway-protoc-gen-openapiv2-0.1.0

**Comment by SID262000** [comment]
@Abe410 At a very high level, seems to be a network issue. Please let me know if you're still facing this issue while deleting the namespaces, Thanks
