### ISSUE TITLE
[Feature] Being able to create multiple Client instances with different api_key

### ISSUE THREAD

**Issue by minzhang-haus** [pinecone-io/pinecone-python-client#213]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing client functionality

### Describe the feature

Hi, in my app, i need to connect to two different pinecone accounts with different api_key. I don't find a way to do it with this lib with pinecone.init. Did i miss something? If not, can we add that as a feature?

**Comment by SID262000** [comment]
@minzhang-haus Do you intend to connect to both the accounts simultaneously?
If I'm thinking in the right direction, you can definitely have 2 different accounts with 2 different api keys.
You can continue to use the pinecone.init to create indexes individually for both the accounts depending on their unique API keys and environments.
Happy to discuss further into the details of the issue

**Comment by daverigby** [comment]
Note that as of [v3.0.0](https://github.com/pinecone-io/pinecone-python-client/releases/tag/v3.0.0), the client has moved away from global state variables to `Pinecone` class instances, which allows you to maintain multiple instances.

For example:
```Python
from pinecone import Pinecone

pc1 = Pinecone(api_key=api_key1)
pc2 =Pinecone(api_key=api_key2)
... Do different operations against the different projects... 
```

References:
* [Readme - Using configuration keyword params](https://github.com/pinecone-io/pinecone-python-client?tab=readme-ov-file#using-configuration-keyword-params)
* [SDK 3 migration guide](https://canyon-quilt-082.notion.site/Pinecone-Python-SDK-v3-0-0-Migration-Guide-056d3897d7634bf7be399676a4757c7b#a21aff70b403416ba352fd30e300bce3)
