### ISSUE TITLE
License Mismatch - Apache or Other/Proprietary

### ISSUE THREAD

**Issue by ChristopherDaigle** [pinecone-io/pinecone-python-client#231]
**Is the license Apache 2.0 or Other/Proprietary?**

Noting the license 

https://github.com/pinecone-io/pinecone-python-client/blob/2b517be75d6141971728889e29aa57cccf17beef/LICENSE.txt#L1-L3

and the .toml

https://github.com/pinecone-io/pinecone-python-client/blob/2b517be75d6141971728889e29aa57cccf17beef/pyproject.toml#L32

[PyPI](https://pypi.org/project/pinecone-client/) has the license listed as [Other/Proprietary License](https://pypi.org/search/?c=License+%3A%3A+Other%2FProprietary+License)

The latter leads to difficulties for usage in differing business operating environments

**Comment by jhamon** [comment]
Hi, thanks for flagging. This field on PyPI should be automatically updated when we publish our next release, but we have not released since the license change was made in the main branch. So for now, there's nothing specific needed here.

**Comment by ChristopherDaigle** [comment]
Thank you @jhamon !
