### ISSUE TITLE
[Bug] Nodes with metadata not found for a short time after persisting in Pinecone

### ISSUE THREAD

**Issue by lmyslinski** [pinecone-io/pinecone-python-client#236]
### Is this a new bug in the Pinecone Python client?

- [X] I believe this is a new bug in the Pinecone Python Client
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Hello,

I'm having an issue with fetching vectors from an index with metadata filtering. Here's the flow:

- I'm parsing some nodes and labelling them with metadata
- I'm storing the nodes in Pinecone
- Immediately after persisting the nodes I query the index for the nodes, however the search turns out empty

I know that the nodes are persisted correctly, but they're not available for retrieval for some period of time after persisting. I've fallen back to using `sleep(30)` after calling persist to around this problem. 10 seconds seems to be not be enough, but 30 gets the job done. 

It seems plausible for the Plausible backend to take a while to build proper indexes for new nodes, but I'd need to reliably be able to tell when I can run my query. If there was some kind of API that can allow me to check whether they're indexed or not that would be great

### Expected Behavior

I can reliably fetch nodes after persisting them in Pinecone

### Steps To Reproduce

Happy to submit a fully reproducible example if needed, just want to confirm that it's an actual bug first

### Environment

```markdown
- OS: MacOS
- Python: 3.11.6
- pinecone: 2.2.4
```

**Comment by lmyslinski** [comment]
I've managed to work around this problem by getting rid of Pinecone, so as far I'm concerned, the problem is "solved"

**Comment by Howe829** [comment]
Same issue here, if you query immediately after upsert you will get empty result.
