### ISSUE TITLE
[Bug] TypeError: query() got multiple values for argument 'top_k'

### ISSUE THREAD

**Issue by rprasanthkumar** [pinecone-io/pinecone-python-client#290]
### Is this a new bug in the Pinecone Python client?

- [X] I believe this is a new bug in the Pinecone Python Client
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

TypeError                                 Traceback (most recent call last)

File ~/.local/lib/python3.8/site-packages/langchain/chains/base.py:181, in Chain.__call__(self, inputs, return_only_outputs, callbacks, tags, metadata, include_run_info)    179 except (KeyboardInterrupt, Exception) as e:    180     run_manager.on_chain_error(e)--> 181     raise e    182 run_manager.on_chain_end(outputs)    183 final_outputs: Dict[str, Any] = self.prep_outputs(    184     inputs, outputs, return_only_outputs    185 )

File ~/.local/lib/python3.8/site-packages/langchain/chains/base.py:175, in Chain.__call__(self, inputs, return_only_outputs, callbacks, tags, metadata, include_run_info)    169 run_manager = callback_manager.on_chain_start(    170     dumpd(self),    171     inputs,    172 )    173 try:    174     outputs = (--> 175         self._call(inputs, run_manager=run_manager)    176         if new_arg_supported    177         else self._call(inputs)    178     )    179 except (KeyboardInterrupt, Exception) as e:    180     run_manager.on_chain_error(e)

File ~/.local/lib/python3.8/site-packages/langchain/chains/retrieval_qa/base.py:128, in BaseRetrievalQA._call(self, inputs, run_manager)    124 accepts_run_manager = (    125     "run_manager" in inspect.signature(self._get_docs).parameters    126 )    127 if accepts_run_manager:--> 128     docs = self._get_docs(question, run_manager=_run_manager)    129 else:    130     docs = self._get_docs(question)  # type: ignore[call-arg]
File ~/.local/lib/python3.8/site-packages/langchain/chains/retrieval_qa/base.py:208, in RetrievalQA._get_docs(self, question, run_manager)    201 def _get_docs(    202     self,    203     question: str,    204     *,    205     run_manager: CallbackManagerForChainRun,    206 ) -> List[Document]:    207     """Get docs."""--> 208     return self.retriever.get_relevant_documents(    209         question, callbacks=run_manager.get_child()    210     )
File ~/.local/lib/python3.8/site-packages/langchain/schema/retriever.py:181, in BaseRetriever.get_relevant_documents(self, query, callbacks, tags, metadata, **kwargs)    179 except Exception as e:    180     run_manager.on_retriever_error(e)--> 181     raise e    182 else:    183     run_manager.on_retriever_end(    184         result,    185         **kwargs,    186     )

File ~/.local/lib/python3.8/site-packages/langchain/schema/retriever.py:174, in BaseRetriever.get_relevant_documents(self, query, callbacks, tags, metadata, **kwargs)    172 _kwargs = kwargs if self._expects_other_args else {}    173 if self._new_arg_supported:--> 174     result = self._get_relevant_documents(    175         query, run_manager=run_manager, **_kwargs    176     )    177 else:    178     result = self._get_relevant_documents(query, **_kwargs)

File ~/.local/lib/python3.8/site-packages/langchain/vectorstores/base.py:413, in VectorStoreRetriever._get_relevant_documents(self, query, run_manager)    409 def _get_relevant_documents(    410     self, query: str, *, run_manager: CallbackManagerForRetrieverRun    411 ) -> List[Document]:    412     if self.search_type == "similarity":--> 413         docs = self.vectorstore.similarity_search(query, **self.search_kwargs)    414     elif self.search_type == "similarity_score_threshold":    415         docs_and_similarities = (    416             self.vectorstore.similarity_search_with_relevance_scores(    417                 query, **self.search_kwargs    418             )    419         )

File ~/.local/lib/python3.8/site-packages/langchain/vectorstores/pinecone.py:158, in Pinecone.similarity_search(self, query, k, filter, namespace, **kwargs)    139 def similarity_search(    140     self,    141     query: str,   (...)    145     **kwargs: Any,    146 ) -> List[Document]:    147     """Return pinecone documents most similar to query.    148     149     Args:   (...)    156         List of Documents most similar to the query and score for each    157     """--> 158     docs_and_scores = self.similarity_search_with_score(    159         query, k=k, filter=filter, namespace=namespace, **kwargs    160     )    161     return [doc for doc, _ in docs_and_scores]

File ~/.local/lib/python3.8/site-packages/langchain/vectorstores/pinecone.py:120, in Pinecone.similarity_search_with_score(self, query, k, filter, namespace)    118 query_obj = self._embedding_function(query)    119 docs = []--> 120 results = self._index.query(    121     [query_obj],    122     top_k=k,    123     include_metadata=True,    124     namespace=namespace,    125     filter=filter,    126 )    127 for res in results["matches"]:    128     metadata = res["metadata"]

File ~/.local/lib/python3.8/site-packages/pinecone/utils/error_handling.py:10, in validate_and_convert_errors.<locals>.inner_func(*args, **kwargs)      7 @wraps(func)      8 def inner_func(*args, **kwargs):      9     try:---> 10         return func(*args, **kwargs)
     11     except MaxRetryError as e:
     12         if isinstance(e.reason, ProtocolError):

TypeError: query() got multiple values for argument 'top_k'

### Expected Behavior

im trying to pass a query but im getting the error, i want retreval output 

### Steps To Reproduce

from langchain.vectorstores import Pinecone
 
text_field = 'Text'  # field in metadata that contains text content
 
vectorstore = Pinecone(
    index, embeddings.embed_query, text_field
)
 
result = vectorstore.similarity_search_with_score("Diabetic Retinopathy Detection",k=3)
result

### Environment

```markdown
- OS: windows 10 using gpu(nvidia A 600)
- Python: 3.11
- pinecone: 3.0.0
```

**Comment by jamescalam** [comment]
hi @rprasanthkumar — this should have been fixed, can you try upgrading your langchain version? This should work:

```
!pip install -qU langchain==0.1.1 langchain-community==0.0.13
```

**Comment by rprasanthkumar** [comment]
> hi @rprasanthkumar — this should have been fixed, can you try upgrading your langchain version? This should work:
> 
> ```
> !pip install -qU langchain==0.1.1 langchain-community==0.0.13
> ```

thankyou Mr.,jamescalam its working
