### ISSUE TITLE
Serverless: Delete all records for a parent document

### ISSUE THREAD

**Issue by bdonkey** [pinecone-io/pinecone-python-client#293]
The [online documentation](https://docs.pinecone.io/docs/manage-rag-documents#delete-all-records-for-a-parent-document) under the **Delete all records for a parent document** heading tells us to first fetch the vectors then delete:
```
To delete all records representing chunks of a single document, 
first fetch the record IDs based on their common ID prefix and then delete the records by ID.
```
The fetch documentation gives us the `curl` command:
```bash
PINECONE_API_KEY="YOUR_API_KEY"
INDEX_HOST="INDEX_HOST"

curl -X POST "https://$INDEX_HOST/vectors/list" \
  -H "Api-Key: $PINECONE_API_KEY" \
  -H 'Content-Type: application/json' \
  -d '{
        "namespace": "ns1",
        "prefix": "doc1#",
        "pagination_token": "c2Vjb25kY2FsbA=="
      }'
```

This command does not work and doesn't make sense? 

If we change the `POST` to a `--request GET` then `fetch` works.

**Comment by opbenesh** [comment]
Hi @bdonkey, thanks for reporting this. There was a mismatch in the documentation, but [the rag page](https://docs.pinecone.io/docs/manage-rag-documents#delete-all-records-for-a-parent-document) has been fixed.
