### ISSUE TITLE
[Bug] Cannot create an index from a source collection in v3

### ISSUE THREAD

**Issue by jacob-petterle** [pinecone-io/pinecone-python-client#294]
### Is this a new bug in the Pinecone Python client?

- [X] I believe this is a new bug in the Pinecone Python Client
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In pinecone v3, neither the `ServerlessSpec` or the `PodSpec` allow creating indexes from a source collection even though the docs show that this is possible:
https://docs.pinecone.io/docs/manage-indexes#create-an-index-from-a-collection

### Expected Behavior

Be able to create both serverless and pod specs from collections

### Steps To Reproduce

1. Create a `Pinecone` instance
2. Using, `pinecone.create_index()`, attempt to create either a pod or serverless based index

### Relevant log output

```shell
NA
```

### Environment

```markdown
NA
```

### Additional Context

[Link to docs](https://docs.pinecone.io/docs/manage-indexes#create-an-index-from-a-collection)

[Link to source code that mismatches](https://github.com/pinecone-io/pinecone-python-client/blob/e100f3c6247d55a9b64a6aaf984a213b9ddb2b19/pinecone/models/pod_spec.py#L3)

**Comment by daverigby** [comment]
This is now possible as of [v3.0.2](https://github.com/pinecone-io/pinecone-python-client/releases/tag/v3.0.2) of the SDK:

> Create indexes using source_collection option in PodSpec
>
> This release resolves a bug when passing source_collection as part of the PodSpec. This option is used when creating a new index from vector data stored in a collection. The value of this field should be a collection you have created previously from an index and that shows with pc.list_collections(). Currently collections and pod-based indexes are not portable across environments.
>  ```Python
> from pinecone import Pinecone
> pc = Pinecone(api_key='YOUR_API_KEY')
>
> pc.create_index(
>    name='my-index', 
>    dimension=1536, 
>    metric='cosine', 
>    spec=PodSpec(
>        environment='us-east1-gcp', 
>        source_collection='collection-2024jan16',
>    )
>)
>```
