### ISSUE TITLE
[Bug] Cant initialize Pinecone class because it says it doesn't have an api_key argument

### ISSUE THREAD

**Issue by juanccontreras8** [pinecone-io/pinecone-python-client#300]
### Is this a new bug in the Pinecone Python client?

- [X] I believe this is a new bug in the Pinecone Python Client
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Pinecone(api_key = ) isn't initializing

### Expected Behavior

Class should initialize

### Steps To Reproduce

```
from pinecone import Pinecone

pc = Pinecone(api_key=os.environ.get('PINECONE_API_KEY'))
```

### Relevant log output

```shell
TypeError: Pinecone.__init__() got an unexpected keyword argument 'api_key'
```

### Environment

```markdown
- OS: Windows 11
- Python:3.10.0
- pinecone: 3.0.1
```

**Comment by ranjanbatra3pg** [comment]
Same is happening with me.

**Comment by UmairAhmadBaltoro** [comment]
```
TypeError: Pinecone.__init__() got an unexpected keyword argument 'api_key'
[2024-02-12 16:16:51,898] ERROR in polling_thread: Error in polling thread: Pinecone.__init__() got an unexpected keyword argument 'api_key'
```

**Comment by ranjanbatra3pg** [comment]
I found out what was causing the error on my side. 
Double check imports - make sure there is no duplicate imports. 
I had an import:
from langchain.vectorstores import Pinecone

**Comment by UmairAhmadBaltoro** [comment]
Thanks. @ranjanbatra3pg  I also had the same issue.
now fixed..
