### ISSUE TITLE
[Bug] Installation snippet with Poetry and GRPC doesn't work

### ISSUE THREAD

**Issue by GameSetAndMatch** [pinecone-io/pinecone-python-client#322]
### Is this a new bug in the Pinecone Python client?

- [X] I believe this is a new bug in the Pinecone Python Client
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In the README doc about installing with Poetry and GRPC, it misses the -client suffix, resulting in an error. 

Right here: https://github.com/pinecone-io/pinecone-python-client?tab=readme-ov-file#initializing-the-client

Just change

`poetry add pinecone --extras grpc`

with 

`poetry add pinecone-client --extras grpc`

### Expected Behavior

Installation of pinecone-client with GRPC working

### Steps To Reproduce

in any poetry environment, just try to install using this command `poetry add pinecone --extras grpc`

### Relevant log output

```shell
poetry add pinecone --extras grpc

Could not find a matching version of package pinecone
```

### Environment

```markdown
- OS:Ubuntu 23.10
- Python:3.11.8
- pinecone: 3.1.0
```

**Comment by daverigby** [comment]
Fixed by #323.
