### ISSUE TITLE
[documentation] DataFrame column name is wrong

### ISSUE THREAD

**Issue by pfrischmann** [pinecone-io/pinecone-python-client#374]
In `upsert_from_dataframe`, the correct DataFrame column name is `values`, and NOT `vector`

https://github.com/pinecone-io/pinecone-python-client/blob/d9df37558ba35b7097dc4bc5c8101b576019caa2/pinecone/data/index.py#L230

**Comment by anawishnoff** [comment]
Hey @jseldess, would you mind making this quick fix?
